// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for NightyNightForRdsFunction
 */
export interface NightyNightForRdsFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/functions/NightyNightForRds.
 */
export class NightyNightForRdsFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: NightyNightForRdsFunctionProps) {
    super(scope, id, {
      description: 'src/functions/NightyNightForRds.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/functions/NightyNightForRds.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}