// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for WakeyWakeyForEc2Function
 */
export interface WakeyWakeyForEc2FunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/functions/WakeyWakeyForEc2.
 */
export class WakeyWakeyForEc2Function extends lambda.Function {
  constructor(scope: Construct, id: string, props?: WakeyWakeyForEc2FunctionProps) {
    super(scope, id, {
      description: 'src/functions/WakeyWakeyForEc2.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/functions/WakeyWakeyForEc2.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}